[phases.setup]
nixPkgs = ["nodejs", "postgresql"]
aptPkgs = []

[phases.install]
cmds = ["cd backend && npm install --production"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && node src/server.js"

